import json
import os
import glob
from collections import defaultdict

def load_json(path):
    with open(path, 'r') as f:
        return json.load(f)

def flatten_tags(tag_dict, tag_name, resolved, resolving):
    if tag_name in resolved:
        return resolved[tag_name]
    
    if tag_name in resolving:
        raise Exception(f"Circular tag reference detected involving {tag_name}")
    
    resolving.add(tag_name)
    result = []
    
    if tag_name in tag_dict:
        for val in tag_dict[tag_name]:
            if val.startswith('#'):
                result.extend(flatten_tags(tag_dict, val[1:], resolved, resolving))
            else:
                result.append(val)
                
    resolved[tag_name] = result
    resolving.remove(tag_name)
    return result

def generate_headers():
    reports_dir = '/home/hamed/projectes/papermc++/mc/generated/reports'
    tags_dir = '/home/hamed/projectes/papermc++/mc/generated/data/minecraft/tags'
    out_dir = '/home/hamed/projectes/papermc++/include/core/protocol/generated'
    os.makedirs(out_dir, exist_ok=True)
    
    # 1. Load registries
    all_registries = {}
    reg_path = os.path.join(reports_dir, 'registries.json')
    if os.path.exists(reg_path):
        all_registries.update(load_json(reg_path))
            
    dp_path = os.path.join(reports_dir, 'datapack.json')
    if os.path.exists(dp_path):
        dp = load_json(dp_path)
        if 'registries' in dp:
            for k, v in dp['registries'].items():
                if k not in all_registries:
                    all_registries[k] = v

    registry_id_map = {}
    
    # Parse all registries
    for reg_name, reg_data in all_registries.items():
        reg_map = {}
        if "entries" in reg_data:
            entries = reg_data["entries"]
            if isinstance(entries, dict):
                for entry_k, entry_v in entries.items():
                    if "protocol_id" in entry_v:
                        reg_map[entry_k] = entry_v["protocol_id"]
                    else:
                        reg_map[entry_k] = len(reg_map)
            elif isinstance(entries, list):
                for i, entry_k in enumerate(entries):
                    reg_map[entry_k] = i
        registry_id_map[reg_name] = reg_map

    # 1. Generate registries.hpp
    reg_content = [
        "// AUTOGENERATED FILE - DO NOT EDIT",
        "#ifndef PAPERMC_CORE_PROTOCOL_GENERATED_REGISTRIES_HPP",
        "#define PAPERMC_CORE_PROTOCOL_GENERATED_REGISTRIES_HPP",
        "",
        "#include <string>",
        "#include <vector>",
        "#include <map>",
        "#include <cstdint>",
        "",
        "namespace papermc::core::protocol::generated {",
        "",
        "    struct RegistryData {",
        "        std::string name;",
        "        std::vector<std::string> entries;",
        "        bool include_overworld_nbt;",
        "    };",
        "",
        "    inline const std::vector<RegistryData> all_registries = {"
    ]
    for reg_name, reg_map in registry_id_map.items():
        include_nbt = "true" if reg_name == "minecraft:dimension_type" else "false"
        reg_content.append(f"        {{\"{reg_name}\", {{")
        
        # Sort by protocol id
        sorted_entries = sorted(reg_map.items(), key=lambda x: x[1])
        for entry_name, _ in sorted_entries:
            reg_content.append(f"            \"{entry_name}\",")
        reg_content.append(f"        }}, {include_nbt}}},")

    reg_content.extend([
        "    };",
        "}",
        "#endif"
    ])
    with open(os.path.join(out_dir, 'registries.hpp'), 'w') as f:
        f.write("\n".join(reg_content) + "\n")


    # 2. Generate tags.hpp
    all_tags = {}
    for root, dirs, files in os.walk(tags_dir):
        for file in files:
            if not file.endswith('.json'):
                continue
            file_path = os.path.join(root, file)
            rel_path = os.path.relpath(file_path, tags_dir)
            parts = rel_path.split(os.sep)
            
            if len(parts) >= 2:
                matched_category = None
                for i in range(len(parts), 0, -1):
                    possible_cat = '/'.join(parts[:i])
                    if f"minecraft:{possible_cat}" in registry_id_map or possible_cat in ["block", "item", "entity_type", "fluid", "game_event"]:
                        matched_category = possible_cat
                        break
                if not matched_category:
                    matched_category = parts[0]
            else:
                matched_category = parts[0]
                
            reg_name = f"minecraft:{matched_category}"
            if reg_name not in all_tags:
                all_tags[reg_name] = {}
                
            tag_rel_path = '/'.join(parts[len(matched_category.split('/')):])
            tag_name = f"minecraft:{tag_rel_path[:-5]}"
            
            tag_data = load_json(file_path)
            values = []
            for val in tag_data.get('values', []):
                if isinstance(val, dict):
                    if val.get('required', True) == False:
                        continue
                    values.append(val['id'])
                else:
                    values.append(val)
            all_tags[reg_name][tag_name] = values

    tag_structs = []
    for reg_name, tags in all_tags.items():
        if reg_name not in registry_id_map:
            continue
        resolved = {}
        resolving = set()
        reg_id_map = registry_id_map[reg_name]
        for tag_name in tags.keys():
            flatten_tags(tags, tag_name, resolved, resolving)
        tag_str = f"        {{\"{reg_name}\", {{\n"
        tag_entries = []
        for tag_name, entries in resolved.items():
            numerical_ids = []
            for e in entries:
                if e in reg_id_map:
                    numerical_ids.append(reg_id_map[e])
                else:
                    e_mc = e if e.startswith('minecraft:') else f"minecraft:{e}"
                    if e_mc in reg_id_map:
                        numerical_ids.append(reg_id_map[e_mc])
            numerical_ids = list(dict.fromkeys(numerical_ids))
            if numerical_ids:
                ids_str = ", ".join(map(str, numerical_ids))
                tag_entries.append(f"            {{\"{tag_name}\", {{{ids_str}}}}}")
            else:
                tag_entries.append(f"            {{\"{tag_name}\", {{}}}}")
        tag_str += ",\n".join(tag_entries)
        tag_str += "\n        }}"
        tag_structs.append(tag_str)

    tag_content = [
        "// AUTOGENERATED FILE - DO NOT EDIT",
        "#ifndef PAPERMC_CORE_PROTOCOL_GENERATED_TAGS_HPP",
        "#define PAPERMC_CORE_PROTOCOL_GENERATED_TAGS_HPP",
        "",
        "#include <string>",
        "#include <vector>",
        "#include <cstdint>",
        "",
        "namespace papermc::core::protocol::generated {",
        "    inline const std::vector<std::pair<std::string, std::vector<std::pair<std::string, std::vector<int32_t>>>>> registry_tags = {",
        ",\n".join(tag_structs),
        "    };",
        "}",
        "#endif"
    ]
    with open(os.path.join(out_dir, 'tags.hpp'), 'w') as f:
        f.write("\n".join(tag_content) + "\n")

    # 3. Generate packets.hpp
    pack_path = os.path.join(reports_dir, 'packets.json')
    pack_content = [
        "// AUTOGENERATED FILE - DO NOT EDIT",
        "#ifndef PAPERMC_CORE_PROTOCOL_GENERATED_PACKETS_HPP",
        "#define PAPERMC_CORE_PROTOCOL_GENERATED_PACKETS_HPP",
        "",
        "#include <string>",
        "#include <cstdint>",
        "",
        "namespace papermc::core::protocol::generated {",
        "    struct PacketIds {"
    ]
    if os.path.exists(pack_path):
        packets_data = load_json(pack_path)
        for state, state_data in packets_data.items():
            for direction, dir_data in state_data.items():
                struct_name = f"{state.capitalize()}{direction.capitalize()}"
                pack_content.append(f"        struct {struct_name} {{")
                for packet_name, packet_info in dir_data.items():
                    name_clean = packet_name.replace("minecraft:", "")
                    pack_content.append(f"            static constexpr int32_t {name_clean} = {packet_info['protocol_id']};")
                pack_content.append("        };")
    pack_content.extend([
        "    };",
        "}",
        "#endif"
    ])
    with open(os.path.join(out_dir, 'packets.hpp'), 'w') as f:
        f.write("\n".join(pack_content) + "\n")


    # 4. Generate blocks.hpp
    blocks_path = os.path.join(reports_dir, 'blocks.json')
    blocks_content = [
        "// AUTOGENERATED FILE - DO NOT EDIT",
        "#ifndef PAPERMC_CORE_PROTOCOL_GENERATED_BLOCKS_HPP",
        "#define PAPERMC_CORE_PROTOCOL_GENERATED_BLOCKS_HPP",
        "",
        "#include <string>",
        "#include <cstdint>",
        "#include <map>",
        "",
        "namespace papermc::core::protocol::generated {",
        "    inline const std::map<std::string, int32_t> block_default_states = {"
    ]
    if os.path.exists(blocks_path):
        blocks_data = load_json(blocks_path)
        for block_name, block_info in blocks_data.items():
            default_id = 0
            for state in block_info.get("states", []):
                if state.get("default", False):
                    default_id = state["id"]
                    break
            blocks_content.append(f"        {{\"{block_name}\", {default_id}}},")
    blocks_content.extend([
        "    };",
        "}",
        "#endif"
    ])
    with open(os.path.join(out_dir, 'blocks.hpp'), 'w') as f:
        f.write("\n".join(blocks_content) + "\n")

if __name__ == '__main__':
    generate_headers()
